/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';

/* CUSTOMER */
export const CUSTOMER_LIST = 'CUSTOMER_LIST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCESS';
export const SUSPEND_CUSTOMER = 'SUSPEND_CUSTOMER';
export const SUSPEND_CUSTOMER_SUCCESS = 'SUSPEND_CUSTOMER_SUCCESS';
export const IMAGES_LIST = 'IMAGES_LIST';
export const IMAGES_LIST_SUCCESS = 'IMAGES_LIST_SUCCESS';
export const CUSTOMER_ONE = 'CUSTOMER_ONE';
export const CUSTOMER_ONE_SUCCESS = 'CUSTOMER_ONE_SUCCESS';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';

/* Notification */
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION';